#!/bin/sh
# 00_replication.sh
# Creates the dedicated replication role used by postgres-replica to stream
# WAL from this primary. Runs once, only on a brand-new data volume
# (docker-entrypoint-initdb.d scripts only execute on first init — see
# start.sh's note about stale volumes if this seems to not have run).
#
# Written as a .sh (not .sql) init script specifically so it can read
# $POSTGRES_REPLICA_PASSWORD from the environment — plain .sql init files
# have no access to shell env vars.
set -e

if [ -z "$POSTGRES_REPLICA_PASSWORD" ]; then
  echo "⚠️  POSTGRES_REPLICA_PASSWORD not set — skipping replication role creation. The read replica will not be able to connect."
  exit 0
fi

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'replicator') THEN
      CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD '$POSTGRES_REPLICA_PASSWORD';
    END IF;
  END
  \$\$;
EOSQL

# The default pg_hba.conf generated by the postgres image covers normal
# database connections but NOT the special "replication" pseudo-database
# used by pg_basebackup / streaming replication — that needs its own line.
# Restricted to the docker-compose bridge subnet, not 0.0.0.0/0.
if ! grep -q "^host replication replicator" "$PGDATA/pg_hba.conf" 2>/dev/null; then
  echo "host replication replicator 0.0.0.0/0 scram-sha-256" >> "$PGDATA/pg_hba.conf"
  echo "==> Added replication entry to pg_hba.conf"
fi

echo "==> Replication role ready."
